name: Metrics
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate isometric commit calendar
      uses: lowlighter/metrics@latest
      with:
        filename: meta/metrics.plugin.isocalendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
  habits:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate coding habits
      uses: lowlighter/metrics@latest
      with:
        filename: meta/metrics.plugin.habits.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_from: 200
        plugin_habits_days: 14
        plugin_habits_facts: yes
        plugin_habits_charts: yes
        plugin_habits_charts_type: classic
        plugin_habits_trim: no
        plugin_habits_languages_limit: 8
        plugin_habits_languages_threshold: "0%"

