     name: Metrics
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate metrics
      uses: lowlighter/metrics@latest
      with:
        template: terminal
        filename: meta/metrics.plugin.languages.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_languages: yes
        plugin_languages_indepth: yes
        # plugin_languages_ignored: >-
        #   html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
        #   gnuplot
        plugin_languages_details: lines, bytes-size, percentage
        plugin_languages_limit: 8
  isocalendar:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate isometric commit calendar
      uses: lowlighter/metrics@latest
      with:
        filename: meta/metrics.plugin.isocalendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
