name: Metrics
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Generate metrics
      uses: lowlighter/metrics@latest
      with:
        template: terminal
        filename: meta/metrics.terminal.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, metadata
